# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - uses: actions/github-script@v5
      with:
        script: |
          function bump {
            local mode="$1"
            local old="$2"
            local parts=( ${old//./ } )
            case "$1" in
              major)
                local bv=$((parts[0] + 1))
                NEW_VERSION="${bv}.0.0"
                ;;
              minor)
                local bv=$((parts[1] + 1))
                NEW_VERSION="${parts[0]}.${bv}.0"
                ;;
              patch)
                local bv=$((parts[2] + 1))
                NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
                ;;
              esac
          }

          git config --global user.email $EMAIL
          git config --global user.name $NAME

          BUMP_MODE="none"
          if git log -1 | grep -q "#major"; then
            BUMP_MODE="major"
          elif git log -1 | grep -q "#minor"; then
            BUMP_MODE="minor"
          elif git log -1 | grep -q "#patch"; then
            BUMP_MODE="patch"
          fi
          $POMPATH=my-app
          echo $BUMP_MODE "version bump detected"
          bump $BUMP_MODE $OLD_VERSION
          echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
          mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file my-app/pom.xml
          git add $POMPATH/pom.xml
          REPO="https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git commit -m "Bump pom.xml from $OLD_VERSION to $NEW_VERSION"
          git tag $NEW_VERSION
          git push $REPO --follow-tags
          git push $REPO --tags
          

    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml
      
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
