# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: |
          [xml]$pomXml = Get-Content my-app\pom.xml
          $oldVersion = [version]$pomXml.project.version   # '1.44.4'
          $newVersion = "{0}.{1}.{2}" -f $oldVersion.Major, $oldVersion.Minor, ($oldVersion.Build + 1)

          Write-Host $newVersion
    
    - uses: actions/github-script@v5
      with:
        script: |
          const diff_url = context.payload.pull_request.diff_url
          const result = await github.request(diff_url)
          console.log(result)
            
    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml
      
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
